name: Al White
favicon: null
layout_spectrum: 0.95491
typography_spectrum: 0.57014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f211d'
    - '#00ffff'
    - '#00adaa'
    - '#9a9b9d'
    - '#dcfdff'
  brandStrength: 0.18727899133227766
  lightness: 0.15938316355459392
  saturation: 0.36735770059749484
  rhythmicContrast: 0.7286874686833471
purpose: []
